---
# Cannot get this to work for some reason
#AWSTemplateFormatVersion: AWSTemplateFormatVersion: '2010-09-09'

Description: This template creates a new Elastic Load Balancer (ELB) into an existing VPC.

Metadata:
    Foo:
        Description: 'something clever'
    Bar:
        Description: 'something clever'

# These show up in the console and are expected to be provided by the operator
Parameters:
    Project:
        Description: 'Project name this cluster is has been created for'
        Type: 'String'
        Default: 'Weapon X'

    Creator:
        Description: 'Tool or person creating this cluster'
        Type: 'String'
        Default: 'CloudFormation'

    Environment:
        Description: 'Context the cluster will be used in.  Common values are production, testing and development.'
        Type: 'String'
        Default: 'development'

    Notes:
        Description: 'Notes to apply, normally edited in the console.'
        Type: 'String'
        Default: 'No notes'

    Subnets:
        Description: 'Which subnets the Applicaion Load Balancer should be deployed to.'
        Type: List<AWS::EC2::Subnet::Id>

    VPC:
        Type: AWS::EC2::VPC::Id
        Description: 'Which VPC the Applicaion Load Balancer should be deployed to.'

    SecurityGroups:
        Description: 'The Security Groups to apply to the Applicaion Load Balancer'
        Type: List<AWS::EC2::SecurityGroup::Id>

    LoadBalancerPort:
        Description: The port the load balancer should listen on
        Type: Number
        Default: 80

    LoadBalancerType:
        Description: Define if the balancer is an external or internal balancer (internet-facing or internal)
        Type: String
        Default: internet-facing

Resources:
    LoadBalancer:
        Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
        Properties:
            LoadBalancerAttributes:
                - Key: 'deletion_protection.enabled'
                  Value: 'false'
                - Key: 'idle_timeout.timeout_seconds'
                  Value: '60'
            Scheme:
                Ref: LoadBalancerType
            SecurityGroups:
                Ref: SecurityGroups
            Subnets:
                Ref: Subnets
            Tags:
                - Key: 'Name'
                  Value: !Ref 'AWS::StackName'
                - Key: 'Project'
                  Value:
                      Ref: 'Project'
                - Key: 'Purpose'
                  Value: 'Load balancer'
                - Key: 'Creator'
                  Value:
                      Ref: 'Creator'
                - Key: 'Environment'
                  Value:
                      Ref: 'Environment'
                - Key: 'Freetext'
                  Value:
                      Ref: Notes

    # We define a default target group here, as this is a mandatory Parameters
    # when creating an Application Load Balancer Listener. This is not used, instead
    # a target group is created per-service in each service template (../services/*)
    DefaultTargetGroup:
        Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
        Properties:
            HealthCheckIntervalSeconds: 10
            HealthCheckPath: '/'
            HealthCheckPort:
                Ref: LoadBalancerPort
            HealthCheckProtocol: HTTP
            HealthCheckTimeoutSeconds: 5
            HealthyThresholdCount: 3
            Matcher:
                HttpCode: '200-399'
            Port:
                Ref: LoadBalancerPort
            Protocol: HTTP
            Tags:
                - Key: 'Name'
                  Value: !Ref 'AWS::StackName'
                - Key: 'Project'
                  Value:
                      Ref: 'Project'
                - Key: 'Purpose'
                  Value: 'Default Group'
                - Key: 'Creator'
                  Value:
                      Ref: 'Creator'
                - Key: 'Environment'
                  Value:
                      Ref: 'Environment'
                - Key: 'Freetext'
                  Value: 'Required but never used by ECS'
            UnhealthyThresholdCount: 3
            VpcId:
                Ref: VPC

    # bind the listener to the target group
    LoadBalancerListener:
        Type: 'AWS::ElasticLoadBalancingV2::Listener'
        Properties:
            DefaultActions:
                - Type: forward
                  TargetGroupArn:
                      Ref: DefaultTargetGroup
            LoadBalancerArn:
                Ref: LoadBalancer
            Port:
                Ref: LoadBalancerPort
            Protocol: HTTP

Outputs:
    LoadBalancer:
        Description: A reference to the Application Load Balancer
        Value:
            Ref: LoadBalancer

    LoadBalancerUrl:
        Description: The URL of the ALB
        Value: !GetAtt LoadBalancer.DNSName

    LoadBalancerListener:
        Description: A reference to the associated listener
        Value:
            Ref: LoadBalancerListener
